[package]
name = "chain-storage"
version = "0.4.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Storage of Crypto.com Chain node (Merkle trie, transaction metadata etc.)"
readme = "README.md"
edition = "2018"

[dependencies]
blake2 = "0.8"
kvdb = "0.5"
kvdb-rocksdb = "0.7"
kvdb-memorydb = "0.5"
chain-core = { path = "../chain-core" }
bit-vec = { version = "0.6.1", features = ["serde_no_std"] }
starling = "3.1.4"
parity-scale-codec = { features = ["derive"], version = "1.2" }
integer-encoding = "1.1.5"

[dev-dependencies]
quickcheck = "0.9"