[package]
name = "tx-validation-enclave"
version = "0.1.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "The transaction validation enclave."
readme = "../../README.md"
edition = "2018"

[lib]
name = "txvalidationenclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tse       = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tstd      = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk", features = ["net","backtrace"] }
sgx_rand      = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_trts      = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_types     = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tseal     = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tcrypto   = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk" }
enclave-macro = { path = "../../enclave-macro" }
chain-tx-validation   = {  path = "../../../chain-tx-validation", default-features = false, features = ["mesalock_sgx"] }
chain-core   = {  path = "../../../chain-core", default-features = false, features = ["mesalock_sgx"] }
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", default-features = false, rev = "d78ae81a598a5ceead03aa1ddf04067f6340f223", features = ["recovery", "endomorphism", "sgx"] }
parity-scale-codec = { default-features = false, version = "1.0" }
enclave-protocol   = { path = "../../../enclave-protocol", default-features = false, features = ["mesalock_sgx"] }
chain-tx-filter   = { path = "../../../chain-tx-filter", default-features = false, features = ["mesalock_sgx"] }
lazy_static  = { version = "1.4", features = ["spin_no_std"] }
