[package]
name = "tx-validation-enclave"
version = "0.2.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "The transaction validation enclave."
readme = "../../README.md"
edition = "2018"

[lib]
name = "tx_validation_enclave"
crate-type = ["lib", "staticlib"]

[features]
default = ["chain-core/default", "chain-tx-filter/default", "enclave-protocol/default", "sgx-wrapper/default"]
sgx-test = []
mesalock_sgx = ["sgx_tstd", "secp256k1zkp/sgx", "enclave-t-common/mesalock_sgx",
                "enclave-protocol/mesalock_sgx", "chain-tx-validation/mesalock_sgx", "chain-core/mesalock_sgx",
                "chain-tx-filter/mesalock_sgx", "sgx-wrapper/mesalock_sgx"]

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types     = { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd      = { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net","backtrace"], optional=true }
sgx-wrapper = { path = "../../../sgx-wrapper", default-features = false }

parity-scale-codec = { default-features = false, version = "1.0" }
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", default-features = false, rev = "0125097a7bf6f939db0ce52e49803c5e0312bf5e", features = ["recovery", "endomorphism"] }
lazy_static  = { version = "1.4", features = ["spin_no_std"] }
aes-gcm-siv = "0.3"
aead = "0.2"

chain-core   = {  path = "../../../chain-core", default-features = false }
enclave-protocol   = { path = "../../../enclave-protocol", default-features = false }
enclave-t-common = { path = "../../enclave-t-common", default-features = false }
chain-tx-filter   = { path = "../../../chain-tx-filter", default-features = false }
chain-tx-validation   = {  path = "../../../chain-tx-validation", default-features = false }

[build-dependencies]
cc = "1.0"
