[package]
name = "enclave-u-common"
version = "0.1.1"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Untrusted enclave-related code."
readme = "../../README.md"
edition = "2018"

[dependencies]
hex = "0.3"
log = "0.4.8"
env_logger = "0.7.0"
sgx_types = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_urts = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git" }