[package]
name = "enclave-u-common"
version = "0.1.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Untrusted enclave-related code."
readme = "../../README.md"
edition = "2018"

[dependencies]
hex = "0.3"
log = "0.4.0"
env_logger = "0.7.0"
sgx_types = { rev = "5b5e512abbbfc3030e8cb274989fb372b685b168", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_urts = { rev = "5b5e512abbbfc3030e8cb274989fb372b685b168", git = "https://github.com/baidu/rust-sgx-sdk" }