[package]
name = "tx-query-app"
version = "0.3.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Application server wrapper around the transaction query enclave (optional)."
readme = "../../README.md"
edition = "2018"

[features]
default = []

[dependencies]
log = "0.4.8"
env_logger = "0.7.0"
enclave-u-common = { path = "../../enclave-u-common" }
sgx_types = { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_urts = { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
parity-scale-codec = { features = ["derive"], version = "1.0" }
chain-core   = { path = "../../../chain-core" }
enclave-protocol   = { path = "../../../enclave-protocol" }
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "0125097a7bf6f939db0ce52e49803c5e0312bf5e", features = ["recovery", "endomorphism"] }
zmq = "0.9"

[build-dependencies]
cc = "1.0"
