[package]
name = "tx-query-app"
version = "0.2.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Application server wrapper around the transaction query enclave (optional)."
readme = "../../README.md"
edition = "2018"

[features]
default = []
sgx-test = ["client-core", "client-common"]

[dependencies]
log = "0.4.8"
env_logger = "0.7.0"
enclave-u-common = { path = "../../enclave-u-common" }
sgx_types = { rev = "5b5e512abbbfc3030e8cb274989fb372b685b168", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_urts = { rev = "5b5e512abbbfc3030e8cb274989fb372b685b168", git = "https://github.com/baidu/rust-sgx-sdk" }
parity-scale-codec = { features = ["derive"], version = "1.0" }
chain-core   = { path = "../../../chain-core" }
enclave-protocol   = { path = "../../../enclave-protocol" }
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "be445f29a96af31fe079611d26c07f1f596d1c5f", features = ["recovery", "endomorphism"] }
zmq = "0.9"
client-core   = { path = "../../../client-core", optional = true }
client-common   = { path = "../../../client-common", optional = true }
