[package]
name = "client-cli"
version = "0.0.1"
authors = ["Devashish Dixit <devashish@crypto.com>"]
edition = "2018"

[dependencies]
chain-core = { path = "../chain-core" }
client-common = { path = "../client-common" }
client-index = { path = "../client-index" }
client-core = { path = "../client-core" }
client-network = { path = "../client-network" }
structopt = "0.3"
quest = "0.3"
secstr = "0.3.2"
hex = "0.3"
prettytable-rs = "0.8"
unicase = "2.5"
chrono = "0.4"
pbr = "1.0"
