[package]
name = "client-cli"
version = "0.1.0"
authors = ["Devashish Dixit <devashish@crypto.com>"]
edition = "2018"

[dependencies]
chain-core = { path = "../chain-core" }
client-common = { path = "../client-common" }
client-core = { path = "../client-core" }
client-network = { path = "../client-network" }
structopt = "0.3"
quest = "0.3"
secstr = { version = "0.3.2", features = ["serde"] }
hex = "0.4"
unicase = "2.5"
chrono = "0.4"
pbr = "1.0"
log = "0.4.8"
env_logger = "0.7.0"
cli-table = "0.1"
