clean_cache: &clean_cache
  language: rust
  sudo: required
  dist: trusty
  if: type = cron
  cache:
    directories: # cargo caching from https://docs.travis-ci.com/user/caching/#rust-cargo-cache
      - $HOME/.cargo
      - $TRAVIS_BUILD_DIR/target
      - $HOME/.rustup/toolchains
      - $HOME/lib
      - $HOME/include
      - $HOME/bin
      - /usr/local/bin # kcov
  install:
  script:
    echo "Cleaning cargo cache ..."
    rm -rf $HOME/.cargo/registry
    rm -rf $HOME/.rustup/toolchains
    cargo clean

rust: &rust
  language: rust
  sudo: required
  dist: trusty
  addons:
    apt:
      packages:
        - libssl-dev
        - libcurl4-openssl-dev
        - libelf-dev
        - libdw-dev
        - cmake
        - gcc
        - binutils-dev
        - libc6-dev
  cache:
    directories:
      - $HOME/.cargo
      - $HOME/.rustup/toolchains
      - $HOME/lib
      - $HOME/include
      - $HOME/bin
  before_cache:
    - du -sh $HOME/.cargo $HOME/.rustup/toolchains $HOME/lib $HOME/include $HOME/bin
    - rm -rf $HOME/.cargo/registry/src
  env:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-Ctarget-feature=+aes,+sse2,+sse4.1,+ssse3 -D warnings"
    - PATH=$HOME/.local/bin:$PATH
    - LD_LIBRARY_PATH=$HOME/lib
    - PKG_CONFIG_PATH=$HOME/lib/pkgconfig
  before_install: # versions from https://github.com/erickt/rust-zmq/blob/master/.travis.yml
    - ./ci-scripts/install_zeromq.sh
    - |
      if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
        ./ci-scripts/install_kcov.sh 
        cargo-kcov --version || cargo install cargo-kcov;
      fi

  script:
    - cargo build
    - cargo build --features http-rpc --manifest-path client-common/Cargo.toml
    - cargo test
    - |
      if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
        (rustfmt --version || rustup component add rustfmt)
        cargo fmt -- --check --color=auto || travis_terminate 1
        (cargo-clippy --version || rustup component add clippy)
        cargo clippy -- -D warnings || travis_terminate 1
        (cargo-audit -h || cargo install cargo-audit)
        cargo audit || travis_terminate 1
      fi

  after_success: |
    if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
      travis_wait 30 cargo kcov --all;
      bash <(curl -s https://codecov.io/bash);
    fi

jobs:
  allow_failures:
    - rust: nightly
  include:
    - <<: *rust
      rust: stable
      if: (type != cron) AND (branch != staging.tmp) AND (branch != trying.tmp)
    - <<: *rust
      rust: beta
      if: (type != cron) AND ((branch = staging) OR (branch = trying))
    - <<: *rust
      rust: nightly
      if: (type != cron) AND (branch != staging.tmp) AND (branch != trying.tmp)

    - <<: *clean_cache
      rust: stable
    - <<: *clean_cache
      rust: beta
    - <<: *clean_cache
      rust: nightly
