clean_cache: &clean_cache
  language: rust
  sudo: required
  dist: xenial
  if: type = cron
  cache:
    directories: # cargo caching from https://docs.travis-ci.com/user/caching/#rust-cargo-cache
      - $HOME/.cargo
      - $TRAVIS_BUILD_DIR/target
      - $HOME/.rustup/toolchains
      - $HOME/lib
      - $HOME/include
      - $HOME/bin
      - /usr/local/bin # kcov
  install:
  script:
    echo "Cleaning cargo cache ..."
    rm -rf $HOME/.cargo/registry
    rm -rf $HOME/.rustup/toolchains
    cargo clean

rust: &rust
  language: rust
  sudo: required
  dist: xenial
  addons:
    apt:
      packages:
        - libssl-dev
        - libcurl4-openssl-dev
        - libelf-dev
        - libdw-dev
        - cmake
        - gcc
        - binutils-dev
        - libc6-dev
        - libzmq3-dev
        - protobuf-compiler
  cache:
    directories:
      - $HOME/.cargo
      - $HOME/.rustup/toolchains
      - $HOME/lib
      - $HOME/include
      - $HOME/bin
  before_cache:
    - du -sh $HOME/.cargo $HOME/.rustup/toolchains $HOME/lib $HOME/include $HOME/bin
    - rm -rf $HOME/.cargo/registry/src
  env:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-Ctarget-feature=+aes,+sse2,+sse4.1,+ssse3 -D warnings"
    - PATH=$HOME/.local/bin:$PATH:/opt/sgxsdk/bin/x64
    - LD_LIBRARY_PATH=$HOME/lib:/opt/sgxsdk/sdk_libs
    - PKG_CONFIG_PATH=$HOME/lib/pkgconfig:/opt/sgxsdk/pkgconfig
    - SGX_SDK=/opt/sgxsdk
    - SGX_MODE=SW
    - NETWORK_ID=ab
  before_install: # versions from https://github.com/erickt/rust-zmq/blob/master/.travis.yml
    - |
      if [[ "$TRAVIS_RUST_VERSION" != nightly ]]; then
        sed -i.bak -E "s/default = \[\".+\"\]/default = \[\"mock-enclave\"\]/" chain-abci/Cargo.toml;
      fi
    - |
      if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
        ./ci-scripts/install_kcov.sh 
        cargo-kcov --version || cargo install cargo-kcov;
      fi

  script:
    - cargo build
    - cargo test
    - |
      if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
        ./ci-scripts/check-docker-app-hash.sh || travis_terminate 1
        (rustfmt --version || rustup component add rustfmt)
        cargo fmt -- --check --color=auto || travis_terminate 1
        (cargo-clippy --version || rustup component add clippy)
        cargo clippy -- -D warnings || travis_terminate 1
        (cargo-audit -h || cargo install cargo-audit)
        cargo audit || travis_terminate 1
      fi

  after_success: |
    if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
      # a small hack, as kcov doesn't have an option to only build default members
      sed 's/"chain-tx-enclave\//#"chain-tx-enclave\//g' -i Cargo.toml;
      # more hacks for kcov :(
      # sed 's/default = \[\]/default = \["mock-enclave"\]/g' -i chain-abci/Cargo.toml;
      # sed 's/sgx/#sgx/g' -i chain-abci/Cargo.toml;
      sed 's/legacy/#legacy/g' -i chain-abci/Cargo.toml;
      sed 's/sgx-test/#sgx-test/g' -i chain-abci/Cargo.toml;
      sed 's/enclave-u-common =/#enclave-u-common =/g' -i chain-abci/Cargo.toml;
      sed 's/sgx_types =/#sgx_types =/g' -i chain-abci/Cargo.toml;
      sed 's/sgx_urts =/#sgx_urts =/g' -i chain-abci/Cargo.toml;
      
      sed 's/CARGO/_CARGO/g' -i chain-abci/build.rs;

      travis_wait 30 cargo kcov --all;
      bash <(curl -s https://codecov.io/bash);
    fi

jobs:
  allow_failures:
    - rust: nightly
  include:
    - <<: *rust
      rust: stable
      if: (type != cron) AND (branch != staging.tmp) AND (branch != trying.tmp)
    - <<: *rust
      rust: beta
      if: (type != cron) AND ((branch = staging) OR (branch = trying))
    - <<: *rust
      rust: nightly
      if: (type != cron) AND (branch != staging.tmp) AND (branch != trying.tmp)

    - <<: *clean_cache
      rust: stable
    - <<: *clean_cache
      rust: beta
    - <<: *clean_cache
      rust: nightly
