[workspace]

members = [
    "chain-abci",
    "chain-core",
    "chain-tx-filter",
    "chain-tx-validation",
    "client-cli",
    "client-common",
    "client-core",
    "client-network",
    "client-rpc",
    "client-mock",
    "dev-utils",
    "enclave-protocol",
]

exclude = [
    # currently only work on nightly + have a different build process
    "chain-tx-enclave/tx-validation/app",
    "chain-tx-enclave/tx-validation/enclave",
    "chain-tx-enclave/tx-query/app",
    "chain-tx-enclave/tx-query/enclave"
]
