[workspace]

members = [
    "chain-abci",
    "chain-core",
    "chain-storage",
    "chain-tx-filter",
    "chain-tx-validation",
    "client-cli",
    "client-common",
    "client-core",
    "client-network",
    "client-rpc",
    "client-rpc/server",
    "test-common",
    "dev-utils",
    "enclave-protocol",
    "chain-tx-enclave/enclave-utils",
    "chain-tx-enclave/enclave-ra/ra-client",
    "chain-tx-enclave/enclave-ra/ra-common",
    "chain-tx-enclave/enclave-ra/ra-enclave",
    "chain-tx-enclave/enclave-ra/ra-sp-client",
    "chain-tx-enclave/enclave-ra/ra-sp-server",
    "chain-tx-enclave/tx-validation/enclave",
    "chain-tx-enclave/tx-query/app",
    "chain-tx-enclave/tx-query/enclave",
    "chain-tx-enclave/tx-query-next/app-runner",
    "chain-tx-enclave/tx-query-next/enclave-app",
    "chain-tx-enclave/mock-utils",
    "cro-clib",
]

default-members = [
    "chain-abci",
    "chain-core",
    "chain-storage",
    "chain-tx-filter",
    "chain-tx-validation",
    "client-cli",
    "client-common",
    "client-core",
    "client-network",
    "client-rpc",
    "client-rpc/server",
    "test-common",
    "dev-utils",
    "enclave-protocol",
    "chain-tx-enclave/enclave-utils",
    "cro-clib",
]

[patch.crates-io]
ring = { git = "https://github.com/crypto-com/ring.git", rev = "f9afbd8a6d571f1a726e1bd1610328623622f2c0" }
