[package]
name = "chain-node"
version = "0.0.1"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Pre-alpha version prototype of Crypto.com Chain node (Tendermint ABCI application)"
readme = "README.md"

[dependencies]
abci = "0.4.3"
chain-core = { path = "chain-core" }
log = "0.4.0"
env_logger = "0.6.0"
bit-vec = "0.5.0"
kvdb = "0.1"
kvdb-rocksdb = "0.1.4"
kvdb-memorydb = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_cbor = "0.9"
serde_json = "1.0"
hex = "0.3"
protobuf = "2.2.0"
integer-encoding = "1.0.5"
clap = { features = ["yaml"], version = "2.32.0" }
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "540cf449b16b4ee4874e9e211a50595e4141d67e" }
blake2 = "0.8"
ethbloom = "0.5.0"

[dev-dependencies]
quickcheck = "0.7"
criterion = "0.2"
digest = "0.8"
sha3 = "0.8"

[[bench]]
name = "hashes"
harness = false

[[bench]]
name = "tx"
harness = false
