[workspace]

members = [
    "chain-abci",
    "chain-core",
    "client-cli",
    "client-common",
    "client-core",
    "client-index",
    "client-rpc",
    "dev-utils",
    "kvdb",
    "kvdb-memorydb",
    "signer-cli",
    "signer-core",
    "signer-rpc",
]
