[package]
name = "tx-query2-app-runner"
version = "0.5.0"
authors = ["Crypto.com <chain@crypto.com>"]
edition = "2018"

[dependencies]
aesm-client = {version = "0.5", features = ["sgxs"] }
async_zmq = "0.3"
enclave-runner = "0.4"
env_logger = "0.7"
futures = "0.3"
log = "0.4"
sgxs-loaders = "0.2"
structopt = "0.3"
tokio = { version = "0.2", features = ["sync", "tcp"] }

enclave-protocol = { path = "../../../enclave-protocol" }
