[package]
name = "tx-query2-enclave-app"
version = "0.6.0"
authors = ["Crypto.com <chain@crypto.com>"]
edition = "2018"

[dependencies]

[target.'cfg(target_env = "sgx")'.dependencies]
env_logger = { version = "0.8", default-features = false }
log = "0.4"
parity-scale-codec = "2.0"
rand = "0.7"
rs-libc = "0.2"
rustls = "0.19"
secp256k1 = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", default-features = false, rev = "1aae6edc5f1de0bbdcdb26f1f1d8b00ca28e012a", features = ["lowmemory", "global-context"] }
thread-pool = "0.1"
zeroize = "1.2"
chrono = "0.4"

chain-core = { path = "../../../chain-core", default-features = false, features = ["edp"] }
enclave-protocol = { path = "../../../enclave-protocol", features = ["edp"] }
enclave-utils = { path = "../../../chain-tx-enclave-next/enclave-utils", features = ["sgxstd"] }
ra-enclave = { path = "../../../chain-tx-enclave-next/enclave-ra/ra-enclave" }
