[package]
name = "signer-core"
version = "0.1.0"
authors = ["Devashish Dixit <devashish@crypto.com>"]
edition = "2018"

[dependencies]
chain-core = { path = "../chain-core/" }
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "99f410ec22c97634e0c430fc578b3a20f30b5ee5", features = ["serde", "zeroize", "rand"] }
rand = "0.6"
failure = "0.1"
zeroize = "0.5"
serde = { version = "1.0", features = ["derive"] }
hex = "0.3"
unicase = "2.2"
sled = "0.18"
bincode = "1.1"
miscreant = "^0.4.2"
blake2 = "0.8"
