[package]
name = "signer-core"
version = "0.1.0"
authors = ["Devashish Dixit <devashish@crypto.com>"]
edition = "2018"

[dependencies]
chain-core = { path = "../chain-core/" }
sha3 = "0.8"
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "540cf449b16b4ee4874e9e211a50595e4141d67e", features = ["serde", "zeroize"] }
rand = "0.6"
failure = "0.1"
zeroize = "0.5"
serde = { version = "1.0", features = ["derive"] }
hex = "0.3"
unicase = "2.2"
