[package]
name = "client-index"
version = "0.1.0"
authors = ["Devashish Dixit <devashish@crypto.com>"]
edition = "2018"

[dependencies]
chain-core = { path = "../chain-core" }
client-common = { path = "../client-common" }
failure = "0.1"
parity-codec = "3.5.1"
parity-codec-derive = "3.3.0"
chrono = { version = "0.4", features = ["serde"] }
jsonrpc = { version = "0.11", optional = true }
base64 = "0.10"

[features]
default = ["sled", "rpc"]
sled = ["client-common/sled"]
rpc = ["jsonrpc"]
