[package]
name = "chain-abci"
version = "0.1.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Pre-alpha version prototype of Crypto.com Chain node (Tendermint ABCI application)"
readme = "README.md"
edition = "2018"

[features]
mock-enc-dec = []
default = ["mock-enc-dec"]

[dependencies]
abci = "0.6"
chain-core = { path = "../chain-core" }
chain-tx-filter = { path = "../chain-tx-filter" }
chain-tx-validation = { path = "../chain-tx-validation" }
enclave-protocol = { path = "../enclave-protocol" }
log = "0.4.8"
env_logger = "0.7.0"
bit-vec = { version = "0.6.1", features = ["serde_no_std"] }
kvdb = "0.1"
kvdb-rocksdb = "0.1.5"
kvdb-memorydb = "0.1"
starling = "3.1.1"
byteorder = "1.3.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
hex = "0.4"
protobuf = "2.7.0"
integer-encoding = "1.0.7"
structopt = "0.3"
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "d78ae81a598a5ceead03aa1ddf04067f6340f223", features = ["recovery", "endomorphism"] }
blake2 = "0.8"
parity-scale-codec = { features = ["derive"], version = "1.0" }
zmq = "0.9"

[dev-dependencies]
quickcheck = "0.9"
# TODO: currently not maintained benchmarks
# criterion = "0.3"
digest = "0.8"
sha3 = "0.8"

# TODO: currently not maintained benchmarks
# [[bench]]
# name = "hashes"
# harness = false

# [[bench]]
# name = "tx"
# harness = false
