[package]
name = "chain-abci"
version = "0.0.1"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Pre-alpha version prototype of Crypto.com Chain node (Tendermint ABCI application)"
readme = "README.md"
edition = "2018"

[features]
mock-enc-dec = []
default = ["mock-enc-dec"]

[dependencies]
abci = "0.6"
chain-core = { path = "../chain-core" }
chain-tx-filter = { path = "../chain-tx-filter" }
chain-tx-validation = { path = "../chain-tx-validation" }
enclave-protocol = { path = "../enclave-protocol" }
log = "0.4.8"
env_logger = "0.6.2"
bit-vec = "0.6.1"
kvdb = "0.1"
kvdb-rocksdb = "0.1.4"
kvdb-memorydb = "0.1"
starling = "3.1.0"
byteorder = "1.3.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
hex = "0.3"
protobuf = "2.7.0"
integer-encoding = "1.0.7"
structopt = "0.2"
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "ac9843a361114b42178acc119ab77d5a149985f5", features = ["recovery", "endomorphism"] }
blake2 = "0.8"
parity-scale-codec = { features = ["derive"], version = "1.0" }
zmq = "0.9"

[dev-dependencies]
quickcheck = "0.8"
criterion = "0.2"
digest = "0.8"
sha3 = "0.8"

[[bench]]
name = "hashes"
harness = false

[[bench]]
name = "tx"
harness = false
