[package]
name = "chain-abci"
version = "0.2.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Pre-alpha version prototype of Crypto.com Chain node (Tendermint ABCI application)"
readme = "README.md"
edition = "2018"

[features]
mock-enc-dec = []
mock-validation = []
default = []

[dependencies]
abci = "0.6"
chain-core = { path = "../chain-core" }
chain-tx-filter = { path = "../chain-tx-filter" }
chain-tx-validation = { path = "../chain-tx-validation" }
enclave-protocol = { path = "../enclave-protocol" }
log = "0.4.8"
env_logger = "0.7.1"
bit-vec = { version = "0.6.1", features = ["serde_no_std"] }
kvdb = "0.2.0"
kvdb-rocksdb = "0.3.0"
kvdb-memorydb = "0.2.0"
starling = "3.1.2"
byteorder = "1.3.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
hex = "0.4"
protobuf = "2.7.0"
integer-encoding = "1.0.7"
structopt = "0.3"
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "be445f29a96af31fe079611d26c07f1f596d1c5f", features = ["recovery", "endomorphism"] }
blake2 = "0.8"
parity-scale-codec = { features = ["derive"], version = "1.1" }
zmq = "0.9"

[dev-dependencies]
quickcheck = "0.9"
# TODO: currently not maintained benchmarks
# criterion = "0.3"
digest = "0.8"
sha3 = "0.8"
base64 = "0.11"
test-common = { path = "../test-common" }

# TODO: currently not maintained benchmarks
# [[bench]]
# name = "hashes"
# harness = false

# [[bench]]
# name = "tx"
# harness = false
