[package]
name = "client-core"
version = "0.1.0"
authors = ["Devashish Dixit <devashish@crypto.com>"]
description = "This crate exposes following functionalities for interacting with Crypto.com Chain."
edition = "2018"

[dependencies]
chain-core = { path = "../chain-core" }
client-common = { path = "../client-common" }
chain-tx-filter = { path = "../chain-tx-filter" }
enclave-protocol = { path = "../enclave-protocol" }
chain-tx-validation = { path = "../chain-tx-validation" }
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "8b9a38b870a7759fcdbd4a5d435b5ba873c70afd", features = ["serde", "zeroize", "rand", "recovery", "endomorphism", "musig"] }
parity-scale-codec = { features = ["derive"], version = "1.0" }
chrono = { version = "0.4", features = ["serde"] }
rand = "0.7"
hex = "0.4"
zeroize = "1.0"
byteorder = "1.3"
secstr = { version = "0.3.2", features = ["serde"] }
itertools = "0.8"
base64 = "0.11"
webpki = "0.21"
rustls =  {version = "0.16", features = ["dangerous_configuration"]}
yasna = { version = "0.3.0", features = ["bit-vec", "num-bigint", "chrono"] }
bit-vec = "0.6.1"
num-bigint = "0.2.3"
serde_json = "1.0.41"
uuid = { version = "0.8.1", features = ["v4"] }
websocket = "0.24.0"
futures = "0.1.29"
jsonrpc-core = "14.0"
log ="0.4.8"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.1.22", default-features = false, features = ["rt-full"] }
tiny-bip39 = { version = "0.6", default-features = false }
unicase = "2.5.1"
lazy_static = "1.4.0"
ring = "0.16.9"

[dev-dependencies]
hex = "0.4.0"
base58 = "0.1.0"
ripemd160 = "0.8.0"

[features]
default = ["sled"]
sled = ["client-common/sled"]
http-rpc = ["client-common/http-rpc"]
websocket-rpc = ["client-common/websocket-rpc"]
