[package]
name = "client-core"
version = "0.1.0"
authors = ["Devashish Dixit <devashish@crypto.com>"]
description = "This crate exposes following functionalities for interacting with Crypto.com Chain."
edition = "2018"

[dependencies]
chain-core = { path = "../chain-core" }
client-common = { path = "../client-common" }
client-index = { path = "../client-index" }
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "4c178ca90965ccf5b1b235e346e836ca65b2a549", features = ["serde", "zeroize", "rand"] }
rand = "0.6"
failure = "0.1"
bincode = "1.1"
hex = "0.3"
zeroize = "0.6"
byteorder = "1.3"
rlp = "0.3"
secstr = "0.3"

[dev-dependencies]
chrono = "0.4"

[features]
default = ["sled", "rpc"]
sled = ["client-common/sled", "client-index/sled"]
rpc = ["client-index/rpc"]
