[package]
name = "client-core"
version = "0.0.3"
authors = ["Devashish Dixit <devashish@crypto.com>"]
description = "This crate exposes following functionalities for interacting with Crypto.com Chain."
edition = "2018"

[dependencies]
chain-core = { path = "../chain-core" }
client-common = { path = "../client-common" }
client-index = { path = "../client-index" }
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "d78ae81a598a5ceead03aa1ddf04067f6340f223", features = ["serde", "zeroize", "rand", "recovery", "endomorphism", "musig"] }
rand = "0.7"
hex = "0.3"
zeroize = "0.10"
byteorder = "1.3"
parity-scale-codec = { features = ["derive"], version = "1.0" }
secstr = "0.3.2"
itertools = "0.8"

[dev-dependencies]
chrono = "0.4"
chain-tx-validation = { path = "../chain-tx-validation" }

[features]
default = ["sled", "rpc"]
sled = ["client-common/sled", "client-index/sled"]
rpc = ["client-index/rpc"]
