[package]
name = "client-rpc"
version = "0.6.0"
authors = ["Crypto.com <chain@crypto.com>"]
edition = "2018"

[features]
mock-enclave = ["client-rpc-core/mock-enclave"]

[dependencies]
client-rpc-core = { path = ".." }
client-core = { path = "../../client-core" }
client-common = { path = "../../client-common" }
client-network = { path= "../../client-network"}
chain-core = { path = "../../chain-core" }

jsonrpc-core = "14.2"
jsonrpc-http-server = "15.0"
structopt = "0.3"
dirs = "3.0.1"
env_logger="0.7.1"
log ="0.4.11"
