[package]
name = "test_cert_expiration"
version = "0.1.0"
authors = ["linfeng <linfeng@crypto.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls =  { version = "0.18", features = ["dangerous_configuration"]  }
webpki = "0.21"
ra-client = { path = "../../../chain-tx-enclave-next/enclave-ra/ra-client" }
enclave-macro = { path = "../../../chain-tx-enclave/enclave-macro" }
