[package]
name = "client-common"
version = "0.1.0"
authors = ["Devashish Dixit <devashish@crypto.com>"]
edition = "2018"

[dependencies]
chain-core = { path = "../chain-core" }
rand = "0.6"
failure = "0.1"
miscreant = "0.4"
blake2 = "0.8"
hex = "0.3"
base64 = "0.10"
secstr = { git = "https://github.com/myfreeweb/secstr", tag = "v0.3.2" }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
sled = { version = "0.24", optional = true }
jsonrpc = { version = "0.11", optional = true }
serde_json = { version = "1.0", optional = true }
parity-codec = { features = ["derive"], version = "3.5.1" }

[features]
default = ["sled", "rpc"]
rpc = ["jsonrpc", "serde_json"]
