[package]
name = "client-common"
version = "0.0.1"
authors = ["Devashish Dixit <devashish@crypto.com>"]
edition = "2018"

[dependencies]
chain-core = { path = "../chain-core" }
chain-tx-filter = { path = "../chain-tx-filter" }
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "ac9843a361114b42178acc119ab77d5a149985f5", features = ["serde", "zeroize", "rand", "recovery", "endomorphism", "musig"] }
rand = "0.7"
miscreant = "0.4"
blake2 = "0.8"
hex = "0.3"
base64 = "0.10"
secstr = "0.3.2"
zeroize = "0.10"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
sled = { version = "0.26", optional = true }
jsonrpc = { version = "0.11", optional = true }
serde_json = { version = "1.0", optional = true }
parity-scale-codec = { features = ["derive"], version = "1.0" }

[features]
default = ["sled", "rpc"]
rpc = ["jsonrpc", "serde_json"]
