[package]
name = "tx-query-enclave"
version = "0.2.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "The transaction query enclave."
readme = "../../README.md"
edition = "2018"

[lib]
name = "tx_query_enclave"
crate-type = ["lib", "staticlib"]

[features]
default = ["sgx-wrapper/default", "chain-core/default", "enclave-protocol/default", "enclave-t-common/default"]
sgx-test = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd", "secp256k1zkp/sgx", "sgx-wrapper/mesalock_sgx", "chain-core/mesalock_sgx", "enclave-protocol/mesalock_sgx", "enclave-t-common/mesalock_sgx"]

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types   = { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd    = { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net"], optional=true }
sgx-wrapper = { path = "../../../sgx-wrapper", default-features=false}

parity-scale-codec = { default-features = false, version = "1.0" }
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", default-features = false, rev = "0125097a7bf6f939db0ce52e49803c5e0312bf5e", features = ["recovery", "endomorphism"] }

chain-core   = { path = "../../../chain-core", default-features = false }
enclave-protocol  = {  path = "../../../enclave-protocol", default-features = false }
enclave-t-common = { path = "../../enclave-t-common", default-features = false }

[build-dependencies]
cc = "1.0"
