[package]
name = "tx-query-enclave"
version = "0.4.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "The transaction query enclave."
readme = "../../README.md"
edition = "2018"

[lib]
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types   = { rev = "v1.1.1", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd    = { rev = "v1.1.1", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net", "thread"] }
sgx_tcrypto = { rev = "v1.1.1", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tse     = { rev = "v1.1.1", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_rand    = { rev = "v1.1.1", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tseal     = { rev = "v1.1.1", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
parity-scale-codec = { default-features = false, features = ["derive"], version = "1.3" }
chain-core   = { path = "../../../chain-core", default-features = false, features = ["mesalock_sgx"] }
enclave-protocol  = {  path = "../../../enclave-protocol", default-features = false, features = ["mesalock_sgx"] }
enclave-t-common = { path = "../../enclave-t-common" }
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", default-features = false, rev = "745bc8d8dc80cb921d5788e863a3536d3b6498a1", features = ["recovery", "endomorphism", "sgx"] }

[dependencies]
chrono      = { git = "https://github.com/mesalock-linux/chrono-sgx", features = ["mesalock_sgx"] }
webpki      = { git = "https://github.com/mesalock-linux/webpki", branch = "mesalock_sgx" }
base64      = { git = "https://github.com/mesalock-linux/rust-base64-sgx", features = ["mesalock_sgx"] }
yasna       = { git = "https://github.com/mesalock-linux/yasna.rs-sgx", features = ["bit-vec", "num-bigint", "chrono"] }
num-bigint  = { git = "https://github.com/mesalock-linux/num-bigint-sgx", features = ["mesalock_sgx"] }
bit-vec     = { version = "0.6.1", default-features = false}
httparse    = { version = "1.3.2", default-features = false }
itertools   = { version = "0.9", default-features = false, features = []}
rustls      = { git = "https://github.com/mesalock-linux/rustls", branch = "mesalock_sgx" }
webpki-roots = { git = "https://github.com/mesalock-linux/webpki-roots", branch = "mesalock_sgx" }
lazy_static  = { version = "1.4", features = ["spin_no_std"] }
zeroize = { version = "1.1", default-features = false, features = ["zeroize_derive"]}

[build-dependencies]
cc = "1.0"
