[package]
name = "ra-sp-server"
version = "0.6.0"
authors = ["Devashish Dixit <devashishdxt@gmail.com>"]
description = "Remote attestation service provider (proxy to IAS and AESM over TCP)"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aesm-client = "0.5"
base64 = "0.12"
env_logger = "0.7"
hex = "0.4"
log = "0.4"
reqwest = { version = "0.10", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde_json = "1.0"
structopt = "0.3"
thiserror = "1.0"

ra-common = { path = "../ra-common" }