[package]
name = "test-common"
version = "0.2.0"
authors = ["yihuang <yi.codeplayer@gmail.com>"]
edition = "2018"

[dependencies]
sha2 = { version = "0.8", default-features = false }
signatory = { version = "0.17", features = ["ed25519", "ecdsa"] }
signatory-dalek = "0.17"
serde_json = { version = "1.0" }
subtle = "2"
subtle-encoding = { version = "0.5", features = ["bech32-preview"] }
secstr = { version = "0.3.2", features = ["serde"] }
lazy_static  = { version = "1.4", features = ["spin_no_std"] }
signature = "1.0.0-pre.1"
abci = "0.6"
kvdb-memorydb = "0.2"
protobuf = "2.7.0"
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "be445f29a96af31fe079611d26c07f1f596d1c5f", features = ["recovery", "endomorphism"] }
parity-scale-codec = { features = ["derive"], version = "1.1" }
base64 = "0.11"
hex = "0.4"

tendermint = { git = "https://github.com/crypto-com/tendermint-rs.git", default-features = false, rev = "a32cec297d80d240781c9ca2aaa71cace93e7510" }
chain-core = { path = "../chain-core" }
chain-abci = { path = "../chain-abci" }
client-common = { path = "../client-common" }
client-core = { path = "../client-core" }
