[package]
name = "tx-validation-app"
version = "0.1.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Application server wrapper around the transaction validation enclave."
readme = "../../README.md"
edition = "2018"

[features]
sgx-test = []

[dependencies]
sled = "0.29"
zmq = "0.9"
log = "0.4.0"
env_logger = "0.7.0"
enclave-u-common = { path = "../../enclave-u-common" }
sgx_types = { rev = "5b5e512abbbfc3030e8cb274989fb372b685b168", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_urts = { rev = "5b5e512abbbfc3030e8cb274989fb372b685b168", git = "https://github.com/baidu/rust-sgx-sdk" }
chain-core   = { path = "../../../chain-core" }
chain-tx-validation   = { path = "../../../chain-tx-validation" }
enclave-protocol   = { path = "../../../enclave-protocol" }
parity-scale-codec = { version = "1.0" }
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "be445f29a96af31fe079611d26c07f1f596d1c5f", features = ["recovery", "endomorphism"] }
