[package]
name = "tx-validation-app"
version = "0.2.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Application server wrapper around the transaction validation enclave."
readme = "../../README.md"
edition = "2018"

[features]
sgx-test = []
mesalock_sgx = ["sgx_urts", "enclave-u-common/mesalock_sgx"]
default = ["tx-validation-enclave"]

[dependencies]
sled = "0.30.3"
zmq = "0.9"
log = "0.4.8"
env_logger = "0.7.0"
enclave-u-common = { path = "../../enclave-u-common", default-features=false }
sgx_types = { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_urts = { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional=true }
chain-core   = { path = "../../../chain-core" }
chain-tx-validation   = { path = "../../../chain-tx-validation" }
enclave-protocol   = { path = "../../../enclave-protocol" }
parity-scale-codec = { version = "1.0" }
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "0125097a7bf6f939db0ce52e49803c5e0312bf5e", features = ["recovery", "endomorphism"] }
tx-validation-enclave = { path = "../enclave", optional=true }

[build-dependencies]
cc = "1.0"
