[package]
name = "tx-query2-app-runner"
version = "0.5.0"
authors = ["Crypto.com <chain@crypto.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
env_logger = "0.7.1"
enclave-runner = "0.3"
sgxs-loaders = "0.2"
aesm-client = {version = "0.4", features = ["sgxs"] }
zmq = "0.9"
tokio = "0.1.22"
enclave-protocol   = { path = "../../../enclave-protocol" }
futures = { version = "0.3.4", features = ["compat", "io-compat"] }
