[package]
name = "chain-core"
version = "0.1.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Library with core types and serialization for the use in external tools"
readme = "../README.md"
edition = "2018"

[features]
default = ["sha3", "serde"]

[dependencies]
digest = "0.8"
sha3 = { version = "0.8", optional = true }
hex = "0.3"
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "aa4f8e08253e7278c20122b9268c970d6f03d44c", features = ["recovery", "endomorphism", "serde"] }
serde = { version = "1.0", features = ["derive"], optional = true }
blake2 = "0.8"
serde_json = "1.0"
parity-codec = { features = ["derive"], version = "4.1.0" }
base64 = "0.10"
static_assertions = "0.3.3"

[dev-dependencies]
quickcheck = "0.8"