[package]
name = "chain-core"
version = "0.1.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Library with core types and serialization for the use in external tools"
readme = "../README.md"
edition = "2018"

[features]
default = ["serde", "bech32"]


[dependencies]
digest = "0.8"
tiny-keccak = { version = "1.5.0", default-features = false, features = ["keccak"] }
hex = "0.3"
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "29991f23eaaa55ec86491dc78e7455f8f1fe3212", features = ["recovery", "endomorphism", "serde"] }
serde = { version = "1.0", features = ["derive"], optional = true }
blake2 = "0.8"
serde_json = "1.0"
parity-scale-codec = { features = ["derive"], version = "1.0" }
base64 = "0.10"
static_assertions = "0.3.3"
bech32 = { version = "0.7.1", optional = true }

[dev-dependencies]
quickcheck = "0.8"