[package]
name = "chain-core"
version = "0.1.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Library with core types and serialization for the use in external tools"
readme = "../README.md"
edition = "2018"

[dependencies]
digest = "0.8"
sha3 = "0.8"
hex = "0.3"
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "99f410ec22c97634e0c430fc578b3a20f30b5ee5" }
serde = { version = "1.0", features = ["derive"] }
blake2 = "0.8"
serde_json = "1.0"
rlp = "0.3.0"
byteorder = "1.3.1"

[dev-dependencies]
quickcheck = "0.8"