[package]
name = "chain-core"
version = "0.1.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Library with core types and serialization for the use in external tools"
readme = "../README.md"
edition = "2018"

[dependencies]
digest = "0.8"
sha3 = "0.8"
hex = "0.3"
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "5b3ec792e8e208771cd54ea807a478f7763e3c69", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
blake2 = "0.8"
serde_json = "1.0"
parity-codec = { features = ["derive"], version = "4.0.0" }
base64 = "0.10"
static_assertions = "0.3.2"

[dev-dependencies]
quickcheck = "0.8"