[package]
name = "ra-enclave"
version = "0.5.0"
authors = ["Devashish Dixit <devashishdxt@gmail.com>"]
description = "Primitives for creating attested TLS server in enclave"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.3"
chrono = "0.4"
cmac = "0.2"
crypto-mac = { version = "0.7", features = ["std"] }
log = "0.4"
rcgen = "0.8"
ring = "0.16"
rustls = "0.17"
serde_json = "1.0"
sgx-isa = { version = "0.3", features = ["sgxstd"] }
sha2 = "0.8"
thiserror = "1.0"

ra-common = { path = "../ra-common" }
ra-sp-client = { path = "../ra-sp-client" }

# Add these lines in workpace Cargo.toml
# [patch.crates-io]
# ring = { git = "https://github.com/crypto-com/ring.git", rev = "f9afbd8a6d571f1a726e1bd1610328623622f2c0" }
