[package]
name = "chain-tx-filter"
version = "0.0.3"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Library that captures the fuctionality related to block-level public view key-based transaction filtering."
readme = "../README.md"
edition = "2018"

[dependencies]
chain-core = { path = "../chain-core" }
parity-scale-codec = { version = "1.0" }
ethbloom = "0.7.0"
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "d78ae81a598a5ceead03aa1ddf04067f6340f223", features = ["endomorphism"] }
