[package]
name = "chain-tx-filter"
version = "0.0.1"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Library that captures the fuctionality related to block-level public view key-based transaction filtering."
readme = "../README.md"
edition = "2018"

[dependencies]
chain-core = { path = "../chain-core" }
parity-scale-codec = { version = "1.0" }
ethbloom = "0.7.0"
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "ac9843a361114b42178acc119ab77d5a149985f5", features = ["endomorphism"] }
