[package]
name = "chain-tx-filter"
version = "0.4.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Library that captures the fuctionality related to block-level public view key-based transaction filtering."
readme = "../README.md"
edition = "2018"

[features]
default = ["bit-vec/std", "chain-core/default"]
mesalock_sgx = ["sgx_tstd", "secp256k1zkp/sgx", "chain-core/mesalock_sgx"]

[dependencies]
chain-core = { default-features = false, path = "../chain-core" }
parity-scale-codec = { default-features = false, version = "1.3" }
secp256k1zkp = { default-features = false, git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", rev = "d50d5998a11064591d86583b297130d6d9636aa5", features = ["endomorphism"] }
bit-vec = { default-features = false, version = "0.6" }
sgx_tstd = { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[dev-dependencies]
quickcheck = "0.9"
hex = "0.4"
ethbloom = "0.9.0"
