[package]
name = "enclave-utils"
version = "0.5.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Platform independent enclave utilities (sealing, attestation primitives...)."
readme = "../../README.md"
edition = "2018"

[dependencies]
sgx-isa = "0.3"
aes-gcm = "0.6"
aead = "0.3"
zeroize = "1.1"
rand = "0.7"

[features]
sgxstd = ["sgx-isa/sgxstd"]
