[package]
name = "client-rpc"
version = "0.1.0"
authors = ["Calvin Lau <calvin@crypto.com>"]
edition = "2018"

[dependencies]
chain-core = { path = "../chain-core" }
client-common = { path = "../client-common" }
client-core = { path = "../client-core" }
client-index = { path = "../client-index" }
failure = "0.1"
jsonrpc-http-server = "11.0"
jsonrpc-derive = "10.1.0"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.2"
chrono = { version = "0.4", features = ["serde"] }
hex = "0.3.2"
