[package]
name = "client-rpc"
version = "0.4.0"
authors = ["Calvin Lau <calvin@crypto.com>"]
edition = "2018"

[features]
mock-enc-dec = []
default = []

[dependencies]
base64 = "0.11"
dirs = "2.0.2"
chain-tx-filter = { path = "../chain-tx-filter" }
chain-core = { path = "../chain-core" }
client-common = { path = "../client-common" }
client-core = { path = "../client-core" }
client-network = { path= "../client-network"}
serde_json = "1.0.49"
jsonrpc-http-server = "14.0"
jsonrpc-core = "14.0"
jsonrpc-core-client = "14.0"
jsonrpc-derive = "14.0"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
chrono = { version = "0.4", features = ["serde"] }
hex = "0.4.2"
secstr = { version = "0.4.0", features = ["serde"] }
env_logger="0.7.1"
log ="0.4.8"
zeroize = "1.1"
tiny-bip39 = { version = "0.7", default-features = false }
indexmap = "1.3"
parity-scale-codec = { features = ["derive"], version = "1.2" }

[dev-dependencies]
parity-scale-codec = "1.2"
