version: "3"

services:
  tendermint:
    image: integration-tests-tendermint
    build:
      context: ../
      dockerfile: ./integration-tests/docker/tendermint/Dockerfile
      args:
        VERSION: ${TENDERMINT_VERSION:-0.30.4}
    environment:
      FEE_SCHEMA: WITHFEE
      PROXY_APP: tcp://chain-abci:26658
    ports:
      - ${TENDERMINT_PORT_P2P:-26656}:26656
      - ${TENDERMINT_PORT_RPC:-26657}:26657
  tendermint-zerofee:
    image: integration-tests-tendermint
    depends_on:
      - tendermint
    environment:
      FEE_SCHEMA: ZEROFEE
      PROXY_APP: tcp://chain-abci-zerofee:26658
    ports:
      - ${TENDERMINT_ZEROFEE_PORT_P2P:-16656}:26656
      - ${TENDERMINT_ZEROFEE_PORT_RPC:-16657}:26657

  chain-abci:
    # Specify image such that it is only build once
    image: integration-tests-chain
    build:
      context: ../
      dockerfile: ./integration-tests/docker/chain/Dockerfile
    command: /usr/bin/chain-abci --host 0.0.0.0 --port 26658 --chain_id ${CHAIN_ID} --genesis_app_hash ${WITHFEE_APP_HASH} --enclave_server tcp://chain-tx-enclave:25933
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: info
    ports:
      - ${CHAIN_ABCI_PORT:-26658}:26658
  chain-abci-zerofee:
    image: integration-tests-chain
    depends_on:
      - chain-abci
    command: /usr/bin/chain-abci --host 0.0.0.0 --port 26658 --chain_id ${CHAIN_ID} --genesis_app_hash ${ZEROFEE_APP_HASH} --enclave_server tcp://chain-tx-enclave-zerofee:25933
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: info
    ports:
      - ${CHAIN_ABCI_ZEROFEE_PORT-16658}:26658

  chain-tx-enclave:
    image: integration-tests-tx-enclave
    build:
      context: ./docker/chain-tx-enclave
      args:
        SGX_MODE: SW
        NETWORK_ID: ${CHAIN_HEX_ID:-AB}
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
  chain-tx-enclave-zerofee:
    image: integration-tests-tx-enclave
    depends_on:
      - chain-tx-enclave
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: debug

  client-rpc:
    image: integration-tests-chain
    depends_on:
      - chain-abci
    command: /usr/bin/wait-for-it.sh tendermint:26657 --strict -- /usr/bin/client-rpc --host 0.0.0.0 --port 26659 --chain-id ${CHAIN_HEX_ID} --storage-dir wallet-storage --tendermint-url http://tendermint:26657
    environment:
      RUST_BACKTRACE: 1
    ports:
      - ${CLIENT_RPC_PORT:-26659}:26659
  client-rpc-zerofee:
    image: integration-tests-chain
    depends_on:
      - chain-abci
    command: /usr/bin/wait-for-it.sh tendermint-zerofee:26657 --strict -- /usr/bin/client-rpc --host 0.0.0.0 --port 26659 --chain-id ${CHAIN_HEX_ID} --storage-dir wallet-storage --tendermint-url http://tendermint-zerofee:26657
    environment:
      RUST_BACKTRACE: 1
    ports:
      - ${CLIENT_RPC_ZEROFEE_PORT:-16659}:26659
