version: "3"

services:
  tendermint:
    image: integration-tests-tendermint
    build:
      context: ../
      dockerfile: ./docker/tendermint-preinit/Dockerfile
    environment:
      PROXY_APP: tcp://chain-abci:26658
    ports:
      - ${TENDERMINT_PORT_P2P-26656}:26656
      - ${TENDERMINT_PORT_RPC-26657}:26657
  tendermint-zerofee:
    image: integration-tests-tendermint
    environment:
      FEE_SCHEMA: ZERO_FEE
      PROXY_APP: tcp://chain-abci-zerofee:26658
    ports:
      - ${TENDERMINT_ZEROFEE_PORT_P2P-16656}:26656
      - ${TENDERMINT_ZEROFEE_PORT_RPC-16657}:26657
  chain-abci:
    # Specify image such that it is only build once
    image: integration-tests-chain
    build:
      context: ../
      dockerfile: ./docker/chain-preinit/Dockerfile
    command: /usr/bin/chain-abci --host 0.0.0.0 --port 26658 --chain_id test-chain-y3m1e6-AB --genesis_app_hash BC80954766B2F82A79DFFB776DB6235DD1CB41B4A945056D8DF8B84B2EAE3F3A
    environment:
      RUST_BACKTRACE: 1
    ports:
      - ${CHAIN_ABCI_PORT-26658}:26658
  chain-abci-zerofee:
    image: integration-tests-chain
    command: /usr/bin/chain-abci --host 0.0.0.0 --port 26658 --chain_id test-chain-y3m1e6-AB --genesis_app_hash BC80954766B2F82A79DFFB776DB6235DD1CB41B4A945056D8DF8B84B2EAE3F3A
    environment:
      RUST_BACKTRACE: 1
    ports:
      - ${CHAIN_ABCI_ZEROFEE_PORT-16658}:26658
  client-rpc:
    image: integration-tests-chain
    depends_on:
      - tendermint
    command: /usr/bin/wait-for-it.sh tendermint:26657 --strict -- /usr/bin/client-rpc --host 0.0.0.0 --port 26659 --chain-id AB --storage-dir .client-rpc-storage --tendermint-url http://tendermint:26657
    environment:
      RUST_BACKTRACE: 1
    ports:
      - ${CLIENT_RPC_PORT-26659}:26659
  client-rpc-zerofee:
    image: integration-tests-chain
    depends_on:
      - tendermint-zerofee
    command: /usr/bin/wait-for-it.sh tendermint-zerofee:26657 --strict -- /usr/bin/client-rpc --host 0.0.0.0 --port 26659 --chain-id AB --storage-dir .client-rpc-storage --tendermint-url http://tendermint-zerofee:26657
    environment:
      RUST_BACKTRACE: 1
    ports:
      - ${CLIENT_RPC_ZEROFEE_PORT-16659}:26659
