[package]
name = "ra-enclave"
version = "0.6.0"
authors = ["Devashish Dixit <devashishdxt@gmail.com>"]
description = "Primitives for creating attested TLS server in enclave"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.4"
chrono = "0.4"
cmac = "0.3"
crypto-mac = { version = "0.8", features = ["std"] }
hex = "0.4"
log = "0.4"
rcgen = "0.8"
ring = "0.16.15"
rustls = "0.19"
serde_json = "1.0"
sgx-isa = { version = "0.3", features = ["sgxstd"] }
sha2 = "0.9"
thiserror = "1.0"

ra-common = { path = "../ra-common" }
ra-sp-client = { path = "../ra-sp-client" }
